### PR TITLE
More helpful demo program

### PR DESCRIPTION
**Pull request by rnbwdsh**
Instead of setting some random colors, I'd prefer if the utility was able to set color | brightness | off out of the box via the python module main via command line arguments.

So I added a color-parser from matplotlib (stackoverflow suggested that's the easiest way to get a colorcode by name), as well as some arguments parsing to allow the params off and brightness.

I also removed the main and util parts, as it was more confusing and tedious to me, than manually using bleak devices. In general, explicit > implicit in python.

Feel free to only take parts of my changes.

### CODE REVIEW

**Comment by itisrazza** [comment]
Thanks for the PR. Sorry I didn't see this 'till now.

I'll take a look at it once I have a computer with a BLE antenna available.

**Comment by itisrazza** [comment]
Is there anyway to make `matplotlib` an optional dependency? It's not strictly needed for the library itself.

**Comment by rnbwdsh** [comment]
It's an option but matplotlib itself doesn't have any (mandatory) dependencies, isn't too big and then we'd at least need to document in the README.md that, to use the supplied color name sample, you have to install the optional package. 

Ideally some ugly in-method-imports (move `from matplotlib.colors import to_rgb` to the line 28 in __main__ and wrapping it into an try-catch-importerror), otherwise, the __main__ would always fail.

So I think it would be more simply to just have it as a regular dependency. But I could refactor it to be optional later this week

**Comment by itisrazza** [comment]
Looks good. I'll merge!

**Pull request merged**
